### ISSUE TITLE
Define boundary between M3 software and M4

### ISSUE THREAD

**Issue by TimBuckers** [project-march/state-machine#13]
We have to find out which code we are going to replace and which we will reuse when running on M3. Also find out if there is integration code needed to make the bridge between M3 software/hardware and M4 software 

- [x] Which nodes are we reusing
- [x] Which code/nodes are we going to write
- [x] Design bridging software between M3 and M4

**Comment by Ishadijcks** [comment]
We will run everything from M3 and send commands from our own nodes
